// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXP9ZwQD-NAOx_D9o-TZFrqpjphmdft08',
    appId: '1:703661084209:web:5e28bb0c63a3ff932acf10',
    messagingSenderId: '703661084209',
    projectId: 'mopet-1658898595272',
    authDomain: 'mopet-1658898595272.firebaseapp.com',
    databaseURL: 'https://mopet-1658898595272-default-rtdb.firebaseio.com',
    storageBucket: 'mopet-1658898595272.appspot.com',
    measurementId: 'G-X5SH9XSPP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_8t67BVLcAXI-Vb_0BxjtrcdcQ9tGE24',
    appId: '1:703661084209:android:927327b090d5559b2acf10',
    messagingSenderId: '703661084209',
    projectId: 'mopet-1658898595272',
    databaseURL: 'https://mopet-1658898595272-default-rtdb.firebaseio.com',
    storageBucket: 'mopet-1658898595272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTFRAXIp8VhHTnSgKZbBWYjI8O-ZiLkt4',
    appId: '1:703661084209:ios:0dd4e5f4222c83952acf10',
    messagingSenderId: '703661084209',
    projectId: 'mopet-1658898595272',
    databaseURL: 'https://mopet-1658898595272-default-rtdb.firebaseio.com',
    storageBucket: 'mopet-1658898595272.appspot.com',
    androidClientId: '703661084209-2ptq7ic0279t9at7khevf0ciev5cu5m5.apps.googleusercontent.com',
    iosBundleId: 'com.bac.mopet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTFRAXIp8VhHTnSgKZbBWYjI8O-ZiLkt4',
    appId: '1:703661084209:ios:815007df0d5ce4512acf10',
    messagingSenderId: '703661084209',
    projectId: 'mopet-1658898595272',
    databaseURL: 'https://mopet-1658898595272-default-rtdb.firebaseio.com',
    storageBucket: 'mopet-1658898595272.appspot.com',
    androidClientId: '703661084209-2ptq7ic0279t9at7khevf0ciev5cu5m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mopet.RunnerTests',
  );
}
